# Generated by Django 5.0.4 on 2024-04-24 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 24, 22, 13, 13, 136250)),
        ),
    ]
